### ISSUE TITLE
Update hero image

### ISSUE THREAD

**Issue by negamorgan** [negamorgan/rebeccahensley.com#1]
changeseeker wrote: "Rather than the first photo with me on the bridge with my thumbs up, I'd rather use the attached photo (DSC_0158) similar to it."

**Comment by negamorgan** [comment]
This fix is done. I think the new photo is less "warm" tho, it's not quite as inviting as the other.

**Comment by negamorgan** [comment]
@changeseeker fyi

**Comment by changeseeker** [comment]
I didn't get back to you last night because I was thinking about all this
and because today and tomorrow are a big two-day event on campus that I
have spearheaded during six months of effort. So my attention has been
required.

But I have freed up Friday/Saturday/Sunday this week to  focus on the
website.

(1) The reason the cover for Why Am I Not Surprised? was an issue is that I
didn't have it yet. In fact, I didn't even have the exact title. I'm
working on both those things now -- with a vengeance. I did take in the
input and look at the examples on story-telling, etc. And I'm putting that
into play.

(2) I will draft text for something about speaking.

(3) The email link is good.

(4) I don't really understand the github addition in the footer, but I
gather it's a stats thing.

(5) Did you mean to write "Get Your Life's Not Over on Amazon now" under
the Make Progress headline rather than "Get Your Life Isn't Over..." (the
actual title)?

(6) Thanks for changing the opening photo.

(7) In the very near future, a 27-minute television interview with me
talking about the diabetes book (shot yesterday morning) will be on
YouTube. At which point, I'd like to add it to the links list at the bottom
of the site.

(8) When I come to visit at Christmas, you can teach me how to maintain the
site myself while we're together. That works better for me than trying to
learn it on the run.

~Mom

**Comment by changeseeker** [comment]
Okay. I've thought about this for a couple of days and taken a good hard
look at the website and I've decided to go with it as is for now with one
exception. I'd like the line under "Make Progress" to read "Get Your Life
Isn't Over" rather than "Get Your Life's Not Over" (to reflect the title).
And as soon as that's done, let's launch it.

I want to add some things to my YouTube list, but I can do that on YouTube.

You can show me how to change the In-Your-Face Women book promo to a Why Am
I Not Surprised? book promo when I'm there next month. By which point, I'll
have the actual cover finished.

And having the email link allows them to ask me to speak, if they want to,
so I feel a need to make that a separate point.

I didn't see this coming, but we're "done" for now. Surprised?

I am.

~Yr Muther

**Comment by negamorgan** [comment]
Okay, will do
